language: c++

matrix:
  include:
    - os: linux
      compiler:
        - gcc
      addons:
        apt:
          update: true
          sources:
            - george-edison55-precise-backports
            - ubuntu-toolchain-r-test
          packages:
            - cmake-data
            - cmake
            - gcc-7

before_install:
  - eval "${MATRIX_EVAL}"

script: scripts/ci/test.sh