language: c++

dist: bionic

matrix:
  include:
    - os: linux
      compiler:
        - gcc
        - clang

before_install:
  - eval "${MATRIX_EVAL}"

script:
  - scripts/linux/ubuntu-install.sh
  - scripts/ci/test.sh