language: c++

dist: bionic

matrix:
  include:
    - os: linux
      compiler:
        - gcc
        - clang
      addons:
        apt:
          packages:
            - libxrandr-dev
            - libxinerama-dev
            - libxcursor-dev
            - libxi-dev

before_install:
  - eval "${MATRIX_EVAL}"

script:
  - scripts/ci/test.sh