language: c++

matrix:
  include:
    - os: linux
      compiler:
        - gcc
        - clang
      addons:
        apt:
          update: true
          sources:
            - george-edison55-precise-backports
          packages:
            - cmake-data
            - cmake

script: script/ci/test.sh