language: c++

dist: bionic
sudo: required

matrix:
  include:
    - os: linux
      compiler:
        - gcc
      addons:
        apt:
          update: true
          sources:
            - george-edison55-precise-backports
          packages:
            - cmake-data
            - cmake

before_install:
  - eval "${MATRIX_EVAL}"

script:
  - ln -s /usr/bin/gcc-7 /usr/local/bin/gcc
  - ln -s /usr/bin/g++-7 /usr/local/bin/g++
  - export CC=/usr/bin/gcc-7
  - export CXX=/usr/bin/g++-7
  - scripts/ci/test.sh