language: c++

dist: bionic

matrix:
  include:
    - os: linux
      compiler:
        - gcc
        - clang
      addons:
        apt:
          packages:
            - libxrandr-dev
            - libxinerama-dev
            - libxcursor-dev
            - libxi-dev
            - libgl1-mesa-dev
            - libglu1-mesa-dev
            - freeglut3-dev
            - mesa-common-dev

before_install:
  - eval "${MATRIX_EVAL}"

script:
  - scripts/test/test.sh --ci